spring:
  datasource:
    url: jdbc:mysql://localhost/test
    username: root
    password: zxc123
    driver-class-name: com.mysql.jdbc.Driver
    #database  pool config
    tomcat:
      # Number of ms to wait before throwing an exception if no connection is available.
      max-wait: 1000
      # Maximum number of active connections that can be allocated from this pool at the same time.
      max-active: 30
      # Validate the connection before borrowing it from the pool.
      test-on-borrow: true
      # initial pool size
      initial-size: 2
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  session:
    timeout: 30
  contextPath: /
  tomcat:
    accesslog:
      enabled: false
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    background-processor-delay: 30


